# Generated by Django 5.0.4 on 2024-05-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='emp_dept',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='emp_dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='emp_img',
            field=models.ImageField(null=True, upload_to='uploadedFiles'),
        ),
    ]
