# Generated by Django 5.0.4 on 2024-05-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employeedata_emp_dept_employeedata_emp_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_last', models.CharField(max_length=20)),
                ('emp_last_name', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(max_length=20)),
                ('emp_mob', models.BigIntegerField()),
                ('emp_queire', models.TextField()),
            ],
        ),
    ]
