# Generated by Django 5.0.4 on 2024-05-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employeedata2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata2',
            name='emp_queire',
        ),
    ]
