# Generated by Django 5.0.4 on 2024-05-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_employeedata2_emp_queire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedata2',
            old_name='emp_first_last',
            new_name='emp_first_name',
        ),
        migrations.AddField(
            model_name='employeedata2',
            name='emp_queire',
            field=models.TextField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
