# Generated by Django 5.2.7 on 2025-12-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata2',
            name='emp_queire',
            field=models.TextField(max_length=200),
        ),
    ]
