# Generated by Django 5.2.7 on 2025-12-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_employeedata2_emp_queire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unm', models.CharField(max_length=100)),
                ('lnm', models.CharField(max_length=100)),
                ('mail_id', models.EmailField(max_length=254)),
                ('mob_no', models.CharField(max_length=15)),
                ('ask', models.TextField()),
            ],
        ),
    ]
